### ISSUE TITLE
Set up kanban board

### ISSUE THREAD

**Issue by codepantha** [codepantherr/medbook-api#7]
[Link to project](https://github.com/users/codepantherr/projects/2)
There are 4 people in my team 👇 
@Amrhub @AlexRS90 @micheaol @codepantherr 
![image](https://user-images.githubusercontent.com/46839548/159980342-85486089-259b-4cba-a800-717317e3df5b.png)

**Comment by MuriloRoque** [comment]
Hi @codepantherr, @micheaol, @Amrhub, @AlexRS90,

In my opinion, your project is complete!

Good luck! 🎉 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
